mysite/myapp/urls.py
from django.urls import path
from myapp.views import (
    index,
    # indexItem,
    add_item,
    update_item,
    delete_item,
    ProductListView,
    ProductDetailView,
    ProductDeleteView,
    # PaymentSuccessView,
    # PaymentFailedView,
    # create_checkout_session,
    # item_details,
)

app_name = "myapp"

urlpatterns = [
    # http://127.0.0.1:8000/myapp/hello/
    path("", index, name="index"),
    # path("", ProductListView.as_view(), name="index"),
    # path("<int:my_id>/", indexItem, name="detail"),
    path("<int:pk>/", ProductDetailView.as_view(), name="detail"),
    # http://127.0.0.1:8000/myapp/contacts/
    # path('contacts/', contacts)
    path("additem/", add_item, name="add_item"),
    path("updateitem/<int:my_id>/", update_item, name="update_item"),
    # path("deleteitem/<int:my_id>/", delete_item, name="delete_item"),
    path("deleteitem/<int:pk>/", ProductDeleteView.as_view(), name="delete_item"),
    # path("success/", PaymentSuccessView.as_view(), name="success"),
    # path("failed/", PaymentFailedView.as_view(), name="failed"),
    # path(
    #     "api/checkout-session/<int:id>/",
    #     create_checkout_session,
    #     name="api_checkout_session",
    # ),
    # path("<int:item_id>/", item_details, name="item_details"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("myapp/", include("myapp.urls", namespace="myapp")),
    path("users/", include("users.urls", namespace="users")),
    path("payments/", include("payments.urls", namespace="payments")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

# from .views import register

from .views import register, logout_view, profile, seller_profile

# from django.contrib.auth import logout

app_name = "users"


# def logout_view(request):
#     logout(request)
#     # Redirect to a success page.


urlpatterns = [
    # http://127.0.0.1:8000/users/
    path("register/", register, name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    # path(
    #     "logout/",
    #     LogoutView.as_view(template_name="users/logout.html", next_page=None),
    #     name="logout",
    # ),
    path("logout/", logout_view, name="logout"),  # Временное решение
    path("profile/", profile, name="profile"),
    path("sellerprofile/<int:id>/", seller_profile, name="sellerprofile"),
]

mysite/myapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default="2")
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to="images")

    def __str__(self):
        return self.name


class OrderDetails(models.Model):
    customer_username = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    amount = models.IntegerField(null=True)
    stripe_payment_intent = models.CharField(max_length=200, null=True)
    has_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.user.username

mysite/myapp/views.py
import json
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Product, OrderDetails


# Create your views here.
def index(request):
    page_obj = items = Product.objects.all()
    item_name = request.GET.get("search")
    if item_name != "" and item_name is not None:
        page_obj = items.filter(name__icontains=item_name)
    paginator = Paginator(page_obj, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    # return HttpResponse(items)
    context = {"page_obj": page_obj}
    return render(request, "myapp/index.html", context)


class ProductListView(ListView):
    model = Product
    template_name = "myapp/index.html"
    context_object_name = "items"
    paginate_by = 2


# def indexItem(request, my_id):
#     item = Product.objects.get(id=my_id)
#     # return HttpResponse('Your item id is:'+ str(my_id))
#     context = {"item": item}
#     return render(request, "myapp/detail.html", context)


class ProductDetailView(DetailView):
    model = Product
    template_name = "myapp/detail.html"
    context_object_name = "item"
    pk_url_kwarg = "pk"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context["stripe_publishable_key"] = settings.STRIPE_PUBLISHABLE_KEY
        return context


@login_required
def add_item(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES["upload"]
        seller = request.user
        item = Product(
            name=name, price=price, description=description, image=image, seller=seller
        )
        item.save()
    return render(request, "myapp/additem.html")


def update_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES.get("upload", item.image)
        item.save()
        return redirect("/myapp/")
    context = {"item": item}
    return render(request, "myapp/updateitem.html", context)


def delete_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.delete()
        return redirect("/myapp/")
    context = {"item": item}
    return render(request, "myapp/deleteitem.html", context)


class ProductDeleteView(DeleteView):
    model = Product
    template_name = "myapp/deleteitem.html"
    success_url = "/myapp/"


# def contacts (request):
#     return render(request,'myapp/contacts.html')
# @csrf_exempt
# def create_checkout_session(request, id):
#     product = get_object_or_404(Product, pk=id)
#     stripe.api_key = settings.STRIPE_SECRET_KEY

#     checkout_session = stripe.checkout.Session.create(
#         # customer_email=request.user.email,
#         payment_method_types=["card"],
#         line_items=[
#             {
#                 "price_data": {
#                     "currency": "usd",
#                     "product_data": {
#                         "name": product.name,
#                     },
#                     "unit_amount": int(product.price * 100),
#                 },
#                 "quantity": 1,
#             }
#         ],
#         mode="payment",
#         success_url=request.build_absolute_uri(reverse("myapp:success"))
#         + "?session_id+{CHECKOUT_SESSION_ID}",
#         cancel_url=request.build_absolute_uri(reverse("myapp:failed")),
#     )
#     order = OrderDetails()
#     # order.customer_username = request.user.username
#     order.product = product
#     order.stripe_payment_intent = checkout_session["payment_intent"]
#     order.amount = int(product.price * 100)
#     order.save()
#     return JsonResponse({"sessionId": checkout_session.id})


# class PaymentSuccessView(TemplateView):
#     template_name = "myapp/payment_success.html"

#     def get(self, request, *args, **kwargs):
#         session_id = request.GET.get("session_id")
#         if session_id is None:
#             return HttpResponseNotFound()

#         stripe.api_key = settings.STRIPE_SECRET_KEY
#         session = stripe.checkout.Session.retrieve(session_id)

#         order = get_object_or_404(
#             OrderDetails, stripe_payment_intent=session.payment_intent
#         )
#         order.has_paid = True
#         order.save()
#         return render(request, self.template_name)


# class PaymentFailedView(TemplateView):
#     template_name = "myapp/payment_failed.html"
# """ def item_details(request, item_id):
#     # Ваш код для обработки запроса с использованием item_id
#     return render(request, "myapp/detail.html", {"item_id": item_id})
#  """

mysite/myapp/templates/myapp/additem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
  <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Item Below</h1>
  <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
      <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text"
        placeholder="Name..." name="name" id="name">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text"
        placeholder="Price..." name="price" id="price">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text"
        placeholder="Description..." name="description" id="description">
      <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
      <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Add
        Item</button>
    </div>
  </form>
</div>
{% endblock content %}

mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
  <link rel="icon" href=" {% static 'images/favicon.ico' %} " type="image/x-icon">
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">

  <title>Document</title>
</head>

<body>
  {% include "myapp/navbar.html"%}
  {% block content%}
  TEXT
  {% endblock content%}
  <!-- {% block content2%}
  TEXT2
  {% endblock content2%} -->

</body>

</html>

mysite/myapp/templates/myapp/deleteitem.html
{% extends "myapp/base.html" %}
{% block content %}
<h1 class="text-2xl m-10 font-bold"> Delete Product</h1>
<form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
  {% csrf_token%}
  <div class="mb-4">
    <label class="block text-gray-500 text-sm font mb-2">Are you sure want to delete this item?</label>
    <label class="block text-gray-500 text-sm font mb-2">{{item.name}}</label>
    <img class="w-40 h-40" src="{{item.image.url}}" alt="" srcset="">


  </div>
  <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">
  <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'myapp:index' %}">Cancel</a>
</form>
{% endblock content %}

mysite/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load humanize %}
{% load static %}

{% block content %}
<div class="flex p-10 w-full h-200">
  <img class="w-1/3" src="{{ item.image.url }}" alt="itemPhoto">
  <div class="w-2/3 text-xl ml-10 mt-5">
    <p class="mt-5">{{ item.name }}</p>
    <p class="mt-5 text-green-500">$ {{ item.price | intcomma }}</p>
    <p class="mt-5 text-gray-600">{{ item.description }}</p>
    <p class="mt-5 text-gray-600"><a href="{% url 'users:sellerprofile' item.seller.id %}">@{{ item.seller }}</a></p>
    <p class="mt-5 text-gray-600">{{ item.seller.profile.contact_number }}</p>
    <button class="bg-green-500 text-white mt-[50px]"><a href="{% url 'myapp:update_item' item.id %}">Update
        Item</a></button>
    <button class="bg-red-500 text-white mt-[50px]"><a href="{% url 'myapp:delete_item' item.id %}">Delete
        Item</a></button>
    <button class="bg-green-500 text-white mt-[50px]" id="submitBtn" data-product-id="{{ item.id }}">Checkout</button>
  </div>

</div>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'payments/main.js' %}"></script>
<script defer src="https://use.fontawesome.com/releases/v6.4.0/js/all.js"></script>
{% endblock content %}

mysite/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

{% block content %}
<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
  <div class="sm:text-center lg:text-left">
    <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block xl:inline">Special Offers </span>
      <span class="block xl:inline text-green-500">Super Prices </span>
    </h1>
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">You can
      order goods from anywhere in the world. Delivery included</p>
  </div>
  <div class="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start p-10">
    <h1>Search</h1>
    <form action="{% url 'myapp:index' %}" method="get">
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-green-500" type="text" name="search"
        id="" placeholder="Search here">
    </form>
  </div>
  <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-3">
    {% for item in page_obj %}
    <a href="{% url 'myapp:detail' item.id %}">
      <div class="rounded overflow-hidden shadow-lg">
        <img class="w-full h-[400px]" src="{{item.image.url}}" alt="">
        <div class="px-6 py-4">
          <p class="font-bold text-xl mb-2"> {{item.name}} </p>
          <p class="font-extrabold text-xl text-green-500 mb-2">$ {{item.price}} </p>
          <p class="font-extrabold text-xl text-indigo-500 mb-2">by: {{item.seller}} </p>
          <p class="text-gray-400 text-base">{{item.description}} </p>

        </div><!--/.px-6 py-4-->
      </div><!--/.rounded overflow-hidden shadow-lg-->

      <!--ID: {{item.id}} | Name: {{item.name}} | Price: {{item.price}} | Description: {{item.description}} <br />-->

    </a>
    {% endfor %}

  </div><!--/.p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-3-->
  <div class="mt-3 text-base text-cyan-600 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
    <span>
      {% if page_obj.has_previous %}
      <a href=" ?page=1">First</a>
      <a href="?page={{page_obj.previous_page_number}}">Previous</a>
      {% endif %}
    </span>
    <span>
      {{page_obj}}
    </span>
    <span>
      {% if page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}">Next</a>
      <a href="?page={{page_obj.paginator.num_pages}}">Last</a>
      {% endif %}
  </div>
</main>
<!--<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-3">-->


{% endblock content %}
<!-- {% block content2 %}
<div class="px-96 py-4">
  <p class="font-bold text-xl text-green-500 mb-2"> Hello </p>
</div>/.px-6 py-4-->
<!-- {% endblock content2 %} -->

mysite/myapp/templates/myapp/navbar.html
{% load static%}
<nav class="bg-white shadow-lg">
  <div class="max-w-6xl mx-auto px-4">
    <div class="flex justify-between">
      <div class="flex space-x-7">
        <div>
          <a href="{% url 'myapp:index'%}" class="flex  items-center px-2 py-4">
            <img class="h-8 w-8" src="{% static 'myapp/images/shop.png' %}" alt="logo" />
            <span class="text-gray-500 font-semibold text-xl"> Pro Shop </span>
          </a><!--/.flex items-center px-2 pu-4-->
        </div>
        <div class="items-center flex space-x-1">
          <a href="{% url 'myapp:index'%}"
            class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
          <a href="{% url 'myapp:add_item'%}" class="py-4 px-2 text-gray-500 font-semibold">Add Item</a>
          <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
          {% if user.is_authenticated %}
          <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
          <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
          {% else %}
          <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div><!--/.flex space-x-7-->
  </div><!--/.flex justify-between-->
  </div><!--/.max-w-6xl mx-auto px-4-->
</nav>

mysite/myapp/templates/myapp/updateitem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
  <h1 class="text-2xl m-10 font-bold text-green-600"> Update New Item Below</h1>
  <form class="w-2/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
      <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 w-full" value="{{item.name}}"
        type="text" placeholder="Name..." name="name" id="name">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 w-full" value="{{item.price}}" type="text"
        placeholder="Price..." name="price" id="price">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 w-full " value="{{item.description}}" type="text"
        placeholder="Description..." name="description" id="description">
      <img class="w-20 h-20" src="{{item.image.url}}" alt="srcset">
        <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
      <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Update Item" value="Update Item">Update
        Item</button>
    </div>
  </form>
</div>
{% endblock content %}